ingress:
  enabled: true
service:
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
login:
  ingress:
    enabled: true
zitadel:
  masterkey: x123456789012345678901234567891y
  selfSignedCert:
    enabled: true
    additionalDnsName: internal-tls.127.0.0.1.sslip.io
  configmapConfig:
    ExternalDomain: internal-tls.127.0.0.1.sslip.io
    ExternalPort: 443
    TLS:
      Enabled: true
      # No need to configure the cert and key path
      # The chart automatically configures them  via environment variables
    Database:
      Postgres:
        Host: db-postgresql
        Port: 5432
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: postgres
          SSL:
            Mode: disable
        Admin:
          Username: postgres
          SSL:
            Mode: disable
