zitadel:
  masterkey: x123456789012345678901234567891y
  configmapConfig:
    ExternalSecure: false
    TLS:
      Enabled: false
    Database:
      cockroach:
        User:
          SSL:
            Mode: "verify-full"
            RootCert: /.secrets/ca.crt
            Cert: /.secrets/tls.crt
            Key: /.secrets/tls.key
        Admin:
          SSL:
            Mode: "verify-full"
