zitadel:
  masterkey: x123456789012345678901234567891y
  configmapConfig:
    ExternalSecure: false
    TLS:
      Enabled: false
  secretConfig:
    Database:
      Cockroach:
        User:
          Password: xyz
