name: Bug Report
description: "Create a bug report to help us improve ZITADEL."
title: "[Bug]: "
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: checkboxes
  id: preflight
  attributes:
    label: Preflight Checklist
    options:
    - label:
        I could not find a solution in the documentation, the existing issues or discussions
      required: true
    - label:
        I have joined the [ZITADEL chat](https://zitadel.com/chat)
- type: input
  id: version
  attributes:
    label: Version
    description: Which version of the Chart are you using.
- type: input
  id: appversion
  attributes:
    label: App version
    description: Which version of ZITADEL are you using.
- type: textarea
  id: impact
  attributes:
    label: Describe the problem caused by this bug
    description: A clear and concise description of the problem you have and what the bug is.
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: To reproduce
    description: Steps to reproduce the behaviour
    placeholder: |
      Steps to reproduce the behavior:
      1. ...
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Logs
    description: If applicable, add relevant logs that could help identifying the cause of your problem. Make sure to redact any sensitive information.
- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
- type: textarea
  id: config
  attributes:
    label: Relevant Configuration
    description: Add any relevant configurations that could help as. Make sure to redact any sensitive information. 
- type: textarea
  id: additional
  attributes:
    label: Additional Context
    description: Please add any other infos that could be useful.
