blank_issues_enabled: true
contact_links:
  - name: 💬 ZITADEL Community Chat
    url: https://zitadel.com/chat
    about: Join our community chat for questions, discussions, and real-time support from the ZITADEL team and community members
