// Code generated by supportgen. DO NOT EDIT.

package support

import (
	require "github.com/stretchr/testify/require"
	assert "github.com/zitadel/zitadel-charts/test/assert"
	v1 "k8s.io/api/admissionregistration/v1"
	v1beta1 "k8s.io/api/admissionregistration/v1beta1"
	v1alpha11 "k8s.io/api/apiserverinternal/v1alpha1"
	v12 "k8s.io/api/apps/v1"
	v2 "k8s.io/api/autoscaling/v2"
	v13 "k8s.io/api/batch/v1"
	v14 "k8s.io/api/certificates/v1"
	v1alpha1 "k8s.io/api/certificates/v1alpha1"
	v1beta11 "k8s.io/api/certificates/v1beta1"
	v15 "k8s.io/api/coordination/v1"
	v1beta12 "k8s.io/api/coordination/v1beta1"
	v16 "k8s.io/api/core/v1"
	v17 "k8s.io/api/discovery/v1"
	v18 "k8s.io/api/flowcontrol/v1"
	v19 "k8s.io/api/networking/v1"
	v110 "k8s.io/api/node/v1"
	v111 "k8s.io/api/policy/v1"
	v112 "k8s.io/api/rbac/v1"
	v113 "k8s.io/api/resource/v1"
	v1alpha3 "k8s.io/api/resource/v1alpha3"
	v114 "k8s.io/api/scheduling/v1"
	v115 "k8s.io/api/storage/v1"
	v1alpha12 "k8s.io/api/storagemigration/v1alpha1"
	errors "k8s.io/apimachinery/pkg/api/errors"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"testing"
)

// GetMutatingWebhookConfiguration fetches a MutatingWebhookConfiguration by name, failing the test on error.
func (env *Env) GetMutatingWebhookConfiguration(t *testing.T, name string) *v1.MutatingWebhookConfiguration {
	t.Helper()
	obj, err := env.Client.AdmissionregistrationV1().MutatingWebhookConfigurations().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get MutatingWebhookConfiguration %s", name)
	return obj
}

// GetMutatingWebhookConfigurationE fetches a MutatingWebhookConfiguration by name, returning the error for non-existence checks.
func (env *Env) GetMutatingWebhookConfigurationE(t *testing.T, name string) (*v1.MutatingWebhookConfiguration, error) {
	t.Helper()
	return env.Client.AdmissionregistrationV1().MutatingWebhookConfigurations().Get(env.Ctx, name, v11.GetOptions{})
}

// GetValidatingAdmissionPolicy fetches a ValidatingAdmissionPolicy by name, failing the test on error.
func (env *Env) GetValidatingAdmissionPolicy(t *testing.T, name string) *v1.ValidatingAdmissionPolicy {
	t.Helper()
	obj, err := env.Client.AdmissionregistrationV1().ValidatingAdmissionPolicies().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ValidatingAdmissionPolicy %s", name)
	return obj
}

// GetValidatingAdmissionPolicyE fetches a ValidatingAdmissionPolicy by name, returning the error for non-existence checks.
func (env *Env) GetValidatingAdmissionPolicyE(t *testing.T, name string) (*v1.ValidatingAdmissionPolicy, error) {
	t.Helper()
	return env.Client.AdmissionregistrationV1().ValidatingAdmissionPolicies().Get(env.Ctx, name, v11.GetOptions{})
}

// GetValidatingAdmissionPolicyBinding fetches a ValidatingAdmissionPolicyBinding by name, failing the test on error.
func (env *Env) GetValidatingAdmissionPolicyBinding(t *testing.T, name string) *v1.ValidatingAdmissionPolicyBinding {
	t.Helper()
	obj, err := env.Client.AdmissionregistrationV1().ValidatingAdmissionPolicyBindings().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ValidatingAdmissionPolicyBinding %s", name)
	return obj
}

// GetValidatingAdmissionPolicyBindingE fetches a ValidatingAdmissionPolicyBinding by name, returning the error for non-existence checks.
func (env *Env) GetValidatingAdmissionPolicyBindingE(t *testing.T, name string) (*v1.ValidatingAdmissionPolicyBinding, error) {
	t.Helper()
	return env.Client.AdmissionregistrationV1().ValidatingAdmissionPolicyBindings().Get(env.Ctx, name, v11.GetOptions{})
}

// GetValidatingWebhookConfiguration fetches a ValidatingWebhookConfiguration by name, failing the test on error.
func (env *Env) GetValidatingWebhookConfiguration(t *testing.T, name string) *v1.ValidatingWebhookConfiguration {
	t.Helper()
	obj, err := env.Client.AdmissionregistrationV1().ValidatingWebhookConfigurations().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ValidatingWebhookConfiguration %s", name)
	return obj
}

// GetValidatingWebhookConfigurationE fetches a ValidatingWebhookConfiguration by name, returning the error for non-existence checks.
func (env *Env) GetValidatingWebhookConfigurationE(t *testing.T, name string) (*v1.ValidatingWebhookConfiguration, error) {
	t.Helper()
	return env.Client.AdmissionregistrationV1().ValidatingWebhookConfigurations().Get(env.Ctx, name, v11.GetOptions{})
}

// GetMutatingAdmissionPolicy fetches a MutatingAdmissionPolicy by name, failing the test on error.
func (env *Env) GetMutatingAdmissionPolicy(t *testing.T, name string) *v1beta1.MutatingAdmissionPolicy {
	t.Helper()
	obj, err := env.Client.AdmissionregistrationV1beta1().MutatingAdmissionPolicies().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get MutatingAdmissionPolicy %s", name)
	return obj
}

// GetMutatingAdmissionPolicyE fetches a MutatingAdmissionPolicy by name, returning the error for non-existence checks.
func (env *Env) GetMutatingAdmissionPolicyE(t *testing.T, name string) (*v1beta1.MutatingAdmissionPolicy, error) {
	t.Helper()
	return env.Client.AdmissionregistrationV1beta1().MutatingAdmissionPolicies().Get(env.Ctx, name, v11.GetOptions{})
}

// GetMutatingAdmissionPolicyBinding fetches a MutatingAdmissionPolicyBinding by name, failing the test on error.
func (env *Env) GetMutatingAdmissionPolicyBinding(t *testing.T, name string) *v1beta1.MutatingAdmissionPolicyBinding {
	t.Helper()
	obj, err := env.Client.AdmissionregistrationV1beta1().MutatingAdmissionPolicyBindings().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get MutatingAdmissionPolicyBinding %s", name)
	return obj
}

// GetMutatingAdmissionPolicyBindingE fetches a MutatingAdmissionPolicyBinding by name, returning the error for non-existence checks.
func (env *Env) GetMutatingAdmissionPolicyBindingE(t *testing.T, name string) (*v1beta1.MutatingAdmissionPolicyBinding, error) {
	t.Helper()
	return env.Client.AdmissionregistrationV1beta1().MutatingAdmissionPolicyBindings().Get(env.Ctx, name, v11.GetOptions{})
}

// GetControllerRevision fetches a ControllerRevision by name, failing the test on error.
func (env *Env) GetControllerRevision(t *testing.T, name string) *v12.ControllerRevision {
	t.Helper()
	obj, err := env.Client.AppsV1().ControllerRevisions(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ControllerRevision %s", name)
	return obj
}

// GetControllerRevisionE fetches a ControllerRevision by name, returning the error for non-existence checks.
func (env *Env) GetControllerRevisionE(t *testing.T, name string) (*v12.ControllerRevision, error) {
	t.Helper()
	return env.Client.AppsV1().ControllerRevisions(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetDaemonSet fetches a DaemonSet by name, failing the test on error.
func (env *Env) GetDaemonSet(t *testing.T, name string) *v12.DaemonSet {
	t.Helper()
	obj, err := env.Client.AppsV1().DaemonSets(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get DaemonSet %s", name)
	return obj
}

// GetDaemonSetE fetches a DaemonSet by name, returning the error for non-existence checks.
func (env *Env) GetDaemonSetE(t *testing.T, name string) (*v12.DaemonSet, error) {
	t.Helper()
	return env.Client.AppsV1().DaemonSets(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetDeployment fetches a Deployment by name, failing the test on error.
func (env *Env) GetDeployment(t *testing.T, name string) *v12.Deployment {
	t.Helper()
	obj, err := env.Client.AppsV1().Deployments(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Deployment %s", name)
	return obj
}

// GetDeploymentE fetches a Deployment by name, returning the error for non-existence checks.
func (env *Env) GetDeploymentE(t *testing.T, name string) (*v12.Deployment, error) {
	t.Helper()
	return env.Client.AppsV1().Deployments(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetReplicaSet fetches a ReplicaSet by name, failing the test on error.
func (env *Env) GetReplicaSet(t *testing.T, name string) *v12.ReplicaSet {
	t.Helper()
	obj, err := env.Client.AppsV1().ReplicaSets(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ReplicaSet %s", name)
	return obj
}

// GetReplicaSetE fetches a ReplicaSet by name, returning the error for non-existence checks.
func (env *Env) GetReplicaSetE(t *testing.T, name string) (*v12.ReplicaSet, error) {
	t.Helper()
	return env.Client.AppsV1().ReplicaSets(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetStatefulSet fetches a StatefulSet by name, failing the test on error.
func (env *Env) GetStatefulSet(t *testing.T, name string) *v12.StatefulSet {
	t.Helper()
	obj, err := env.Client.AppsV1().StatefulSets(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get StatefulSet %s", name)
	return obj
}

// GetStatefulSetE fetches a StatefulSet by name, returning the error for non-existence checks.
func (env *Env) GetStatefulSetE(t *testing.T, name string) (*v12.StatefulSet, error) {
	t.Helper()
	return env.Client.AppsV1().StatefulSets(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetHorizontalPodAutoscaler fetches a HorizontalPodAutoscaler by name, failing the test on error.
func (env *Env) GetHorizontalPodAutoscaler(t *testing.T, name string) *v2.HorizontalPodAutoscaler {
	t.Helper()
	obj, err := env.Client.AutoscalingV2().HorizontalPodAutoscalers(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get HorizontalPodAutoscaler %s", name)
	return obj
}

// GetHorizontalPodAutoscalerE fetches a HorizontalPodAutoscaler by name, returning the error for non-existence checks.
func (env *Env) GetHorizontalPodAutoscalerE(t *testing.T, name string) (*v2.HorizontalPodAutoscaler, error) {
	t.Helper()
	return env.Client.AutoscalingV2().HorizontalPodAutoscalers(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetCronJob fetches a CronJob by name, failing the test on error.
func (env *Env) GetCronJob(t *testing.T, name string) *v13.CronJob {
	t.Helper()
	obj, err := env.Client.BatchV1().CronJobs(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get CronJob %s", name)
	return obj
}

// GetCronJobE fetches a CronJob by name, returning the error for non-existence checks.
func (env *Env) GetCronJobE(t *testing.T, name string) (*v13.CronJob, error) {
	t.Helper()
	return env.Client.BatchV1().CronJobs(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetJob fetches a Job by name, failing the test on error.
func (env *Env) GetJob(t *testing.T, name string) *v13.Job {
	t.Helper()
	obj, err := env.Client.BatchV1().Jobs(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Job %s", name)
	return obj
}

// GetJobE fetches a Job by name, returning the error for non-existence checks.
func (env *Env) GetJobE(t *testing.T, name string) (*v13.Job, error) {
	t.Helper()
	return env.Client.BatchV1().Jobs(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetCertificateSigningRequest fetches a CertificateSigningRequest by name, failing the test on error.
func (env *Env) GetCertificateSigningRequest(t *testing.T, name string) *v14.CertificateSigningRequest {
	t.Helper()
	obj, err := env.Client.CertificatesV1().CertificateSigningRequests().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get CertificateSigningRequest %s", name)
	return obj
}

// GetCertificateSigningRequestE fetches a CertificateSigningRequest by name, returning the error for non-existence checks.
func (env *Env) GetCertificateSigningRequestE(t *testing.T, name string) (*v14.CertificateSigningRequest, error) {
	t.Helper()
	return env.Client.CertificatesV1().CertificateSigningRequests().Get(env.Ctx, name, v11.GetOptions{})
}

// GetPodCertificateRequest fetches a PodCertificateRequest by name, failing the test on error.
func (env *Env) GetPodCertificateRequest(t *testing.T, name string) *v1alpha1.PodCertificateRequest {
	t.Helper()
	obj, err := env.Client.CertificatesV1alpha1().PodCertificateRequests(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get PodCertificateRequest %s", name)
	return obj
}

// GetPodCertificateRequestE fetches a PodCertificateRequest by name, returning the error for non-existence checks.
func (env *Env) GetPodCertificateRequestE(t *testing.T, name string) (*v1alpha1.PodCertificateRequest, error) {
	t.Helper()
	return env.Client.CertificatesV1alpha1().PodCertificateRequests(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetClusterTrustBundle fetches a ClusterTrustBundle by name, failing the test on error.
func (env *Env) GetClusterTrustBundle(t *testing.T, name string) *v1beta11.ClusterTrustBundle {
	t.Helper()
	obj, err := env.Client.CertificatesV1beta1().ClusterTrustBundles().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ClusterTrustBundle %s", name)
	return obj
}

// GetClusterTrustBundleE fetches a ClusterTrustBundle by name, returning the error for non-existence checks.
func (env *Env) GetClusterTrustBundleE(t *testing.T, name string) (*v1beta11.ClusterTrustBundle, error) {
	t.Helper()
	return env.Client.CertificatesV1beta1().ClusterTrustBundles().Get(env.Ctx, name, v11.GetOptions{})
}

// GetLease fetches a Lease by name, failing the test on error.
func (env *Env) GetLease(t *testing.T, name string) *v15.Lease {
	t.Helper()
	obj, err := env.Client.CoordinationV1().Leases(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Lease %s", name)
	return obj
}

// GetLeaseE fetches a Lease by name, returning the error for non-existence checks.
func (env *Env) GetLeaseE(t *testing.T, name string) (*v15.Lease, error) {
	t.Helper()
	return env.Client.CoordinationV1().Leases(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetLeaseCandidate fetches a LeaseCandidate by name, failing the test on error.
func (env *Env) GetLeaseCandidate(t *testing.T, name string) *v1beta12.LeaseCandidate {
	t.Helper()
	obj, err := env.Client.CoordinationV1beta1().LeaseCandidates(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get LeaseCandidate %s", name)
	return obj
}

// GetLeaseCandidateE fetches a LeaseCandidate by name, returning the error for non-existence checks.
func (env *Env) GetLeaseCandidateE(t *testing.T, name string) (*v1beta12.LeaseCandidate, error) {
	t.Helper()
	return env.Client.CoordinationV1beta1().LeaseCandidates(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetComponentStatus fetches a ComponentStatus by name, failing the test on error.
func (env *Env) GetComponentStatus(t *testing.T, name string) *v16.ComponentStatus {
	t.Helper()
	obj, err := env.Client.CoreV1().ComponentStatuses().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ComponentStatus %s", name)
	return obj
}

// GetComponentStatusE fetches a ComponentStatus by name, returning the error for non-existence checks.
func (env *Env) GetComponentStatusE(t *testing.T, name string) (*v16.ComponentStatus, error) {
	t.Helper()
	return env.Client.CoreV1().ComponentStatuses().Get(env.Ctx, name, v11.GetOptions{})
}

// GetConfigMap fetches a ConfigMap by name, failing the test on error.
func (env *Env) GetConfigMap(t *testing.T, name string) *v16.ConfigMap {
	t.Helper()
	obj, err := env.Client.CoreV1().ConfigMaps(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ConfigMap %s", name)
	return obj
}

// GetConfigMapE fetches a ConfigMap by name, returning the error for non-existence checks.
func (env *Env) GetConfigMapE(t *testing.T, name string) (*v16.ConfigMap, error) {
	t.Helper()
	return env.Client.CoreV1().ConfigMaps(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetEndpoints fetches a Endpoints by name, failing the test on error.
func (env *Env) GetEndpoints(t *testing.T, name string) *v16.Endpoints {
	t.Helper()
	obj, err := env.Client.CoreV1().Endpoints(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Endpoints %s", name)
	return obj
}

// GetEndpointsE fetches a Endpoints by name, returning the error for non-existence checks.
func (env *Env) GetEndpointsE(t *testing.T, name string) (*v16.Endpoints, error) {
	t.Helper()
	return env.Client.CoreV1().Endpoints(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetEvent fetches a Event by name, failing the test on error.
func (env *Env) GetEvent(t *testing.T, name string) *v16.Event {
	t.Helper()
	obj, err := env.Client.CoreV1().Events(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Event %s", name)
	return obj
}

// GetEventE fetches a Event by name, returning the error for non-existence checks.
func (env *Env) GetEventE(t *testing.T, name string) (*v16.Event, error) {
	t.Helper()
	return env.Client.CoreV1().Events(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetLimitRange fetches a LimitRange by name, failing the test on error.
func (env *Env) GetLimitRange(t *testing.T, name string) *v16.LimitRange {
	t.Helper()
	obj, err := env.Client.CoreV1().LimitRanges(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get LimitRange %s", name)
	return obj
}

// GetLimitRangeE fetches a LimitRange by name, returning the error for non-existence checks.
func (env *Env) GetLimitRangeE(t *testing.T, name string) (*v16.LimitRange, error) {
	t.Helper()
	return env.Client.CoreV1().LimitRanges(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetNamespace fetches a Namespace by name, failing the test on error.
func (env *Env) GetNamespace(t *testing.T, name string) *v16.Namespace {
	t.Helper()
	obj, err := env.Client.CoreV1().Namespaces().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Namespace %s", name)
	return obj
}

// GetNamespaceE fetches a Namespace by name, returning the error for non-existence checks.
func (env *Env) GetNamespaceE(t *testing.T, name string) (*v16.Namespace, error) {
	t.Helper()
	return env.Client.CoreV1().Namespaces().Get(env.Ctx, name, v11.GetOptions{})
}

// GetNode fetches a Node by name, failing the test on error.
func (env *Env) GetNode(t *testing.T, name string) *v16.Node {
	t.Helper()
	obj, err := env.Client.CoreV1().Nodes().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Node %s", name)
	return obj
}

// GetNodeE fetches a Node by name, returning the error for non-existence checks.
func (env *Env) GetNodeE(t *testing.T, name string) (*v16.Node, error) {
	t.Helper()
	return env.Client.CoreV1().Nodes().Get(env.Ctx, name, v11.GetOptions{})
}

// GetPersistentVolume fetches a PersistentVolume by name, failing the test on error.
func (env *Env) GetPersistentVolume(t *testing.T, name string) *v16.PersistentVolume {
	t.Helper()
	obj, err := env.Client.CoreV1().PersistentVolumes().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get PersistentVolume %s", name)
	return obj
}

// GetPersistentVolumeE fetches a PersistentVolume by name, returning the error for non-existence checks.
func (env *Env) GetPersistentVolumeE(t *testing.T, name string) (*v16.PersistentVolume, error) {
	t.Helper()
	return env.Client.CoreV1().PersistentVolumes().Get(env.Ctx, name, v11.GetOptions{})
}

// GetPersistentVolumeClaim fetches a PersistentVolumeClaim by name, failing the test on error.
func (env *Env) GetPersistentVolumeClaim(t *testing.T, name string) *v16.PersistentVolumeClaim {
	t.Helper()
	obj, err := env.Client.CoreV1().PersistentVolumeClaims(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get PersistentVolumeClaim %s", name)
	return obj
}

// GetPersistentVolumeClaimE fetches a PersistentVolumeClaim by name, returning the error for non-existence checks.
func (env *Env) GetPersistentVolumeClaimE(t *testing.T, name string) (*v16.PersistentVolumeClaim, error) {
	t.Helper()
	return env.Client.CoreV1().PersistentVolumeClaims(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetPod fetches a Pod by name, failing the test on error.
func (env *Env) GetPod(t *testing.T, name string) *v16.Pod {
	t.Helper()
	obj, err := env.Client.CoreV1().Pods(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Pod %s", name)
	return obj
}

// GetPodE fetches a Pod by name, returning the error for non-existence checks.
func (env *Env) GetPodE(t *testing.T, name string) (*v16.Pod, error) {
	t.Helper()
	return env.Client.CoreV1().Pods(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetPodTemplate fetches a PodTemplate by name, failing the test on error.
func (env *Env) GetPodTemplate(t *testing.T, name string) *v16.PodTemplate {
	t.Helper()
	obj, err := env.Client.CoreV1().PodTemplates(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get PodTemplate %s", name)
	return obj
}

// GetPodTemplateE fetches a PodTemplate by name, returning the error for non-existence checks.
func (env *Env) GetPodTemplateE(t *testing.T, name string) (*v16.PodTemplate, error) {
	t.Helper()
	return env.Client.CoreV1().PodTemplates(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetReplicationController fetches a ReplicationController by name, failing the test on error.
func (env *Env) GetReplicationController(t *testing.T, name string) *v16.ReplicationController {
	t.Helper()
	obj, err := env.Client.CoreV1().ReplicationControllers(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ReplicationController %s", name)
	return obj
}

// GetReplicationControllerE fetches a ReplicationController by name, returning the error for non-existence checks.
func (env *Env) GetReplicationControllerE(t *testing.T, name string) (*v16.ReplicationController, error) {
	t.Helper()
	return env.Client.CoreV1().ReplicationControllers(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetResourceQuota fetches a ResourceQuota by name, failing the test on error.
func (env *Env) GetResourceQuota(t *testing.T, name string) *v16.ResourceQuota {
	t.Helper()
	obj, err := env.Client.CoreV1().ResourceQuotas(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ResourceQuota %s", name)
	return obj
}

// GetResourceQuotaE fetches a ResourceQuota by name, returning the error for non-existence checks.
func (env *Env) GetResourceQuotaE(t *testing.T, name string) (*v16.ResourceQuota, error) {
	t.Helper()
	return env.Client.CoreV1().ResourceQuotas(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetSecret fetches a Secret by name, failing the test on error.
func (env *Env) GetSecret(t *testing.T, name string) *v16.Secret {
	t.Helper()
	obj, err := env.Client.CoreV1().Secrets(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Secret %s", name)
	return obj
}

// GetSecretE fetches a Secret by name, returning the error for non-existence checks.
func (env *Env) GetSecretE(t *testing.T, name string) (*v16.Secret, error) {
	t.Helper()
	return env.Client.CoreV1().Secrets(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetService fetches a Service by name, failing the test on error.
func (env *Env) GetService(t *testing.T, name string) *v16.Service {
	t.Helper()
	obj, err := env.Client.CoreV1().Services(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Service %s", name)
	return obj
}

// GetServiceE fetches a Service by name, returning the error for non-existence checks.
func (env *Env) GetServiceE(t *testing.T, name string) (*v16.Service, error) {
	t.Helper()
	return env.Client.CoreV1().Services(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetServiceAccount fetches a ServiceAccount by name, failing the test on error.
func (env *Env) GetServiceAccount(t *testing.T, name string) *v16.ServiceAccount {
	t.Helper()
	obj, err := env.Client.CoreV1().ServiceAccounts(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ServiceAccount %s", name)
	return obj
}

// GetServiceAccountE fetches a ServiceAccount by name, returning the error for non-existence checks.
func (env *Env) GetServiceAccountE(t *testing.T, name string) (*v16.ServiceAccount, error) {
	t.Helper()
	return env.Client.CoreV1().ServiceAccounts(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetEndpointSlice fetches a EndpointSlice by name, failing the test on error.
func (env *Env) GetEndpointSlice(t *testing.T, name string) *v17.EndpointSlice {
	t.Helper()
	obj, err := env.Client.DiscoveryV1().EndpointSlices(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get EndpointSlice %s", name)
	return obj
}

// GetEndpointSliceE fetches a EndpointSlice by name, returning the error for non-existence checks.
func (env *Env) GetEndpointSliceE(t *testing.T, name string) (*v17.EndpointSlice, error) {
	t.Helper()
	return env.Client.DiscoveryV1().EndpointSlices(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetFlowSchema fetches a FlowSchema by name, failing the test on error.
func (env *Env) GetFlowSchema(t *testing.T, name string) *v18.FlowSchema {
	t.Helper()
	obj, err := env.Client.FlowcontrolV1().FlowSchemas().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get FlowSchema %s", name)
	return obj
}

// GetFlowSchemaE fetches a FlowSchema by name, returning the error for non-existence checks.
func (env *Env) GetFlowSchemaE(t *testing.T, name string) (*v18.FlowSchema, error) {
	t.Helper()
	return env.Client.FlowcontrolV1().FlowSchemas().Get(env.Ctx, name, v11.GetOptions{})
}

// GetPriorityLevelConfiguration fetches a PriorityLevelConfiguration by name, failing the test on error.
func (env *Env) GetPriorityLevelConfiguration(t *testing.T, name string) *v18.PriorityLevelConfiguration {
	t.Helper()
	obj, err := env.Client.FlowcontrolV1().PriorityLevelConfigurations().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get PriorityLevelConfiguration %s", name)
	return obj
}

// GetPriorityLevelConfigurationE fetches a PriorityLevelConfiguration by name, returning the error for non-existence checks.
func (env *Env) GetPriorityLevelConfigurationE(t *testing.T, name string) (*v18.PriorityLevelConfiguration, error) {
	t.Helper()
	return env.Client.FlowcontrolV1().PriorityLevelConfigurations().Get(env.Ctx, name, v11.GetOptions{})
}

// GetStorageVersion fetches a StorageVersion by name, failing the test on error.
func (env *Env) GetStorageVersion(t *testing.T, name string) *v1alpha11.StorageVersion {
	t.Helper()
	obj, err := env.Client.InternalV1alpha1().StorageVersions().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get StorageVersion %s", name)
	return obj
}

// GetStorageVersionE fetches a StorageVersion by name, returning the error for non-existence checks.
func (env *Env) GetStorageVersionE(t *testing.T, name string) (*v1alpha11.StorageVersion, error) {
	t.Helper()
	return env.Client.InternalV1alpha1().StorageVersions().Get(env.Ctx, name, v11.GetOptions{})
}

// GetIPAddress fetches a IPAddress by name, failing the test on error.
func (env *Env) GetIPAddress(t *testing.T, name string) *v19.IPAddress {
	t.Helper()
	obj, err := env.Client.NetworkingV1().IPAddresses().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get IPAddress %s", name)
	return obj
}

// GetIPAddressE fetches a IPAddress by name, returning the error for non-existence checks.
func (env *Env) GetIPAddressE(t *testing.T, name string) (*v19.IPAddress, error) {
	t.Helper()
	return env.Client.NetworkingV1().IPAddresses().Get(env.Ctx, name, v11.GetOptions{})
}

// GetIngress fetches a Ingress by name, failing the test on error.
func (env *Env) GetIngress(t *testing.T, name string) *v19.Ingress {
	t.Helper()
	obj, err := env.Client.NetworkingV1().Ingresses(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Ingress %s", name)
	return obj
}

// GetIngressE fetches a Ingress by name, returning the error for non-existence checks.
func (env *Env) GetIngressE(t *testing.T, name string) (*v19.Ingress, error) {
	t.Helper()
	return env.Client.NetworkingV1().Ingresses(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetIngressClass fetches a IngressClass by name, failing the test on error.
func (env *Env) GetIngressClass(t *testing.T, name string) *v19.IngressClass {
	t.Helper()
	obj, err := env.Client.NetworkingV1().IngressClasses().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get IngressClass %s", name)
	return obj
}

// GetIngressClassE fetches a IngressClass by name, returning the error for non-existence checks.
func (env *Env) GetIngressClassE(t *testing.T, name string) (*v19.IngressClass, error) {
	t.Helper()
	return env.Client.NetworkingV1().IngressClasses().Get(env.Ctx, name, v11.GetOptions{})
}

// GetNetworkPolicy fetches a NetworkPolicy by name, failing the test on error.
func (env *Env) GetNetworkPolicy(t *testing.T, name string) *v19.NetworkPolicy {
	t.Helper()
	obj, err := env.Client.NetworkingV1().NetworkPolicies(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get NetworkPolicy %s", name)
	return obj
}

// GetNetworkPolicyE fetches a NetworkPolicy by name, returning the error for non-existence checks.
func (env *Env) GetNetworkPolicyE(t *testing.T, name string) (*v19.NetworkPolicy, error) {
	t.Helper()
	return env.Client.NetworkingV1().NetworkPolicies(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetServiceCIDR fetches a ServiceCIDR by name, failing the test on error.
func (env *Env) GetServiceCIDR(t *testing.T, name string) *v19.ServiceCIDR {
	t.Helper()
	obj, err := env.Client.NetworkingV1().ServiceCIDRs().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ServiceCIDR %s", name)
	return obj
}

// GetServiceCIDRE fetches a ServiceCIDR by name, returning the error for non-existence checks.
func (env *Env) GetServiceCIDRE(t *testing.T, name string) (*v19.ServiceCIDR, error) {
	t.Helper()
	return env.Client.NetworkingV1().ServiceCIDRs().Get(env.Ctx, name, v11.GetOptions{})
}

// GetRuntimeClass fetches a RuntimeClass by name, failing the test on error.
func (env *Env) GetRuntimeClass(t *testing.T, name string) *v110.RuntimeClass {
	t.Helper()
	obj, err := env.Client.NodeV1().RuntimeClasses().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get RuntimeClass %s", name)
	return obj
}

// GetRuntimeClassE fetches a RuntimeClass by name, returning the error for non-existence checks.
func (env *Env) GetRuntimeClassE(t *testing.T, name string) (*v110.RuntimeClass, error) {
	t.Helper()
	return env.Client.NodeV1().RuntimeClasses().Get(env.Ctx, name, v11.GetOptions{})
}

// GetPodDisruptionBudget fetches a PodDisruptionBudget by name, failing the test on error.
func (env *Env) GetPodDisruptionBudget(t *testing.T, name string) *v111.PodDisruptionBudget {
	t.Helper()
	obj, err := env.Client.PolicyV1().PodDisruptionBudgets(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get PodDisruptionBudget %s", name)
	return obj
}

// GetPodDisruptionBudgetE fetches a PodDisruptionBudget by name, returning the error for non-existence checks.
func (env *Env) GetPodDisruptionBudgetE(t *testing.T, name string) (*v111.PodDisruptionBudget, error) {
	t.Helper()
	return env.Client.PolicyV1().PodDisruptionBudgets(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetClusterRole fetches a ClusterRole by name, failing the test on error.
func (env *Env) GetClusterRole(t *testing.T, name string) *v112.ClusterRole {
	t.Helper()
	obj, err := env.Client.RbacV1().ClusterRoles().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ClusterRole %s", name)
	return obj
}

// GetClusterRoleE fetches a ClusterRole by name, returning the error for non-existence checks.
func (env *Env) GetClusterRoleE(t *testing.T, name string) (*v112.ClusterRole, error) {
	t.Helper()
	return env.Client.RbacV1().ClusterRoles().Get(env.Ctx, name, v11.GetOptions{})
}

// GetClusterRoleBinding fetches a ClusterRoleBinding by name, failing the test on error.
func (env *Env) GetClusterRoleBinding(t *testing.T, name string) *v112.ClusterRoleBinding {
	t.Helper()
	obj, err := env.Client.RbacV1().ClusterRoleBindings().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ClusterRoleBinding %s", name)
	return obj
}

// GetClusterRoleBindingE fetches a ClusterRoleBinding by name, returning the error for non-existence checks.
func (env *Env) GetClusterRoleBindingE(t *testing.T, name string) (*v112.ClusterRoleBinding, error) {
	t.Helper()
	return env.Client.RbacV1().ClusterRoleBindings().Get(env.Ctx, name, v11.GetOptions{})
}

// GetRole fetches a Role by name, failing the test on error.
func (env *Env) GetRole(t *testing.T, name string) *v112.Role {
	t.Helper()
	obj, err := env.Client.RbacV1().Roles(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get Role %s", name)
	return obj
}

// GetRoleE fetches a Role by name, returning the error for non-existence checks.
func (env *Env) GetRoleE(t *testing.T, name string) (*v112.Role, error) {
	t.Helper()
	return env.Client.RbacV1().Roles(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetRoleBinding fetches a RoleBinding by name, failing the test on error.
func (env *Env) GetRoleBinding(t *testing.T, name string) *v112.RoleBinding {
	t.Helper()
	obj, err := env.Client.RbacV1().RoleBindings(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get RoleBinding %s", name)
	return obj
}

// GetRoleBindingE fetches a RoleBinding by name, returning the error for non-existence checks.
func (env *Env) GetRoleBindingE(t *testing.T, name string) (*v112.RoleBinding, error) {
	t.Helper()
	return env.Client.RbacV1().RoleBindings(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetDeviceClass fetches a DeviceClass by name, failing the test on error.
func (env *Env) GetDeviceClass(t *testing.T, name string) *v113.DeviceClass {
	t.Helper()
	obj, err := env.Client.ResourceV1().DeviceClasses().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get DeviceClass %s", name)
	return obj
}

// GetDeviceClassE fetches a DeviceClass by name, returning the error for non-existence checks.
func (env *Env) GetDeviceClassE(t *testing.T, name string) (*v113.DeviceClass, error) {
	t.Helper()
	return env.Client.ResourceV1().DeviceClasses().Get(env.Ctx, name, v11.GetOptions{})
}

// GetResourceClaim fetches a ResourceClaim by name, failing the test on error.
func (env *Env) GetResourceClaim(t *testing.T, name string) *v113.ResourceClaim {
	t.Helper()
	obj, err := env.Client.ResourceV1().ResourceClaims(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ResourceClaim %s", name)
	return obj
}

// GetResourceClaimE fetches a ResourceClaim by name, returning the error for non-existence checks.
func (env *Env) GetResourceClaimE(t *testing.T, name string) (*v113.ResourceClaim, error) {
	t.Helper()
	return env.Client.ResourceV1().ResourceClaims(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetResourceClaimTemplate fetches a ResourceClaimTemplate by name, failing the test on error.
func (env *Env) GetResourceClaimTemplate(t *testing.T, name string) *v113.ResourceClaimTemplate {
	t.Helper()
	obj, err := env.Client.ResourceV1().ResourceClaimTemplates(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ResourceClaimTemplate %s", name)
	return obj
}

// GetResourceClaimTemplateE fetches a ResourceClaimTemplate by name, returning the error for non-existence checks.
func (env *Env) GetResourceClaimTemplateE(t *testing.T, name string) (*v113.ResourceClaimTemplate, error) {
	t.Helper()
	return env.Client.ResourceV1().ResourceClaimTemplates(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetResourceSlice fetches a ResourceSlice by name, failing the test on error.
func (env *Env) GetResourceSlice(t *testing.T, name string) *v113.ResourceSlice {
	t.Helper()
	obj, err := env.Client.ResourceV1().ResourceSlices().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get ResourceSlice %s", name)
	return obj
}

// GetResourceSliceE fetches a ResourceSlice by name, returning the error for non-existence checks.
func (env *Env) GetResourceSliceE(t *testing.T, name string) (*v113.ResourceSlice, error) {
	t.Helper()
	return env.Client.ResourceV1().ResourceSlices().Get(env.Ctx, name, v11.GetOptions{})
}

// GetDeviceTaintRule fetches a DeviceTaintRule by name, failing the test on error.
func (env *Env) GetDeviceTaintRule(t *testing.T, name string) *v1alpha3.DeviceTaintRule {
	t.Helper()
	obj, err := env.Client.ResourceV1alpha3().DeviceTaintRules().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get DeviceTaintRule %s", name)
	return obj
}

// GetDeviceTaintRuleE fetches a DeviceTaintRule by name, returning the error for non-existence checks.
func (env *Env) GetDeviceTaintRuleE(t *testing.T, name string) (*v1alpha3.DeviceTaintRule, error) {
	t.Helper()
	return env.Client.ResourceV1alpha3().DeviceTaintRules().Get(env.Ctx, name, v11.GetOptions{})
}

// GetPriorityClass fetches a PriorityClass by name, failing the test on error.
func (env *Env) GetPriorityClass(t *testing.T, name string) *v114.PriorityClass {
	t.Helper()
	obj, err := env.Client.SchedulingV1().PriorityClasses().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get PriorityClass %s", name)
	return obj
}

// GetPriorityClassE fetches a PriorityClass by name, returning the error for non-existence checks.
func (env *Env) GetPriorityClassE(t *testing.T, name string) (*v114.PriorityClass, error) {
	t.Helper()
	return env.Client.SchedulingV1().PriorityClasses().Get(env.Ctx, name, v11.GetOptions{})
}

// GetCSIDriver fetches a CSIDriver by name, failing the test on error.
func (env *Env) GetCSIDriver(t *testing.T, name string) *v115.CSIDriver {
	t.Helper()
	obj, err := env.Client.StorageV1().CSIDrivers().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get CSIDriver %s", name)
	return obj
}

// GetCSIDriverE fetches a CSIDriver by name, returning the error for non-existence checks.
func (env *Env) GetCSIDriverE(t *testing.T, name string) (*v115.CSIDriver, error) {
	t.Helper()
	return env.Client.StorageV1().CSIDrivers().Get(env.Ctx, name, v11.GetOptions{})
}

// GetCSINode fetches a CSINode by name, failing the test on error.
func (env *Env) GetCSINode(t *testing.T, name string) *v115.CSINode {
	t.Helper()
	obj, err := env.Client.StorageV1().CSINodes().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get CSINode %s", name)
	return obj
}

// GetCSINodeE fetches a CSINode by name, returning the error for non-existence checks.
func (env *Env) GetCSINodeE(t *testing.T, name string) (*v115.CSINode, error) {
	t.Helper()
	return env.Client.StorageV1().CSINodes().Get(env.Ctx, name, v11.GetOptions{})
}

// GetCSIStorageCapacity fetches a CSIStorageCapacity by name, failing the test on error.
func (env *Env) GetCSIStorageCapacity(t *testing.T, name string) *v115.CSIStorageCapacity {
	t.Helper()
	obj, err := env.Client.StorageV1().CSIStorageCapacities(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get CSIStorageCapacity %s", name)
	return obj
}

// GetCSIStorageCapacityE fetches a CSIStorageCapacity by name, returning the error for non-existence checks.
func (env *Env) GetCSIStorageCapacityE(t *testing.T, name string) (*v115.CSIStorageCapacity, error) {
	t.Helper()
	return env.Client.StorageV1().CSIStorageCapacities(env.Kube.Namespace).Get(env.Ctx, name, v11.GetOptions{})
}

// GetStorageClass fetches a StorageClass by name, failing the test on error.
func (env *Env) GetStorageClass(t *testing.T, name string) *v115.StorageClass {
	t.Helper()
	obj, err := env.Client.StorageV1().StorageClasses().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get StorageClass %s", name)
	return obj
}

// GetStorageClassE fetches a StorageClass by name, returning the error for non-existence checks.
func (env *Env) GetStorageClassE(t *testing.T, name string) (*v115.StorageClass, error) {
	t.Helper()
	return env.Client.StorageV1().StorageClasses().Get(env.Ctx, name, v11.GetOptions{})
}

// GetVolumeAttachment fetches a VolumeAttachment by name, failing the test on error.
func (env *Env) GetVolumeAttachment(t *testing.T, name string) *v115.VolumeAttachment {
	t.Helper()
	obj, err := env.Client.StorageV1().VolumeAttachments().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get VolumeAttachment %s", name)
	return obj
}

// GetVolumeAttachmentE fetches a VolumeAttachment by name, returning the error for non-existence checks.
func (env *Env) GetVolumeAttachmentE(t *testing.T, name string) (*v115.VolumeAttachment, error) {
	t.Helper()
	return env.Client.StorageV1().VolumeAttachments().Get(env.Ctx, name, v11.GetOptions{})
}

// GetVolumeAttributesClass fetches a VolumeAttributesClass by name, failing the test on error.
func (env *Env) GetVolumeAttributesClass(t *testing.T, name string) *v115.VolumeAttributesClass {
	t.Helper()
	obj, err := env.Client.StorageV1().VolumeAttributesClasses().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get VolumeAttributesClass %s", name)
	return obj
}

// GetVolumeAttributesClassE fetches a VolumeAttributesClass by name, returning the error for non-existence checks.
func (env *Env) GetVolumeAttributesClassE(t *testing.T, name string) (*v115.VolumeAttributesClass, error) {
	t.Helper()
	return env.Client.StorageV1().VolumeAttributesClasses().Get(env.Ctx, name, v11.GetOptions{})
}

// GetStorageVersionMigration fetches a StorageVersionMigration by name, failing the test on error.
func (env *Env) GetStorageVersionMigration(t *testing.T, name string) *v1alpha12.StorageVersionMigration {
	t.Helper()
	obj, err := env.Client.StoragemigrationV1alpha1().StorageVersionMigrations().Get(env.Ctx, name, v11.GetOptions{})
	require.NoError(t, err, "failed to get StorageVersionMigration %s", name)
	return obj
}

// GetStorageVersionMigrationE fetches a StorageVersionMigration by name, returning the error for non-existence checks.
func (env *Env) GetStorageVersionMigrationE(t *testing.T, name string) (*v1alpha12.StorageVersionMigration, error) {
	t.Helper()
	return env.Client.StoragemigrationV1alpha1().StorageVersionMigrations().Get(env.Ctx, name, v11.GetOptions{})
}

// AssertPartial fetches the K8s resource implied by the assertion type and
// performs a partial assertion. The resource type is inferred from the
// concrete assertion struct via a type switch.
func (env *Env) AssertPartial(t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch a := assertion.(type) {
	case assert.ControllerRevisionAssertion:
		assert.AssertPartial(t, env.GetControllerRevision(t, name), a, name)
	case assert.DaemonSetAssertion:
		assert.AssertPartial(t, env.GetDaemonSet(t, name), a, name)
	case assert.DeploymentAssertion:
		assert.AssertPartial(t, env.GetDeployment(t, name), a, name)
	case assert.ReplicaSetAssertion:
		assert.AssertPartial(t, env.GetReplicaSet(t, name), a, name)
	case assert.StatefulSetAssertion:
		assert.AssertPartial(t, env.GetStatefulSet(t, name), a, name)
	case assert.HorizontalPodAutoscalerAssertion:
		assert.AssertPartial(t, env.GetHorizontalPodAutoscaler(t, name), a, name)
	case assert.CronJobAssertion:
		assert.AssertPartial(t, env.GetCronJob(t, name), a, name)
	case assert.JobAssertion:
		assert.AssertPartial(t, env.GetJob(t, name), a, name)
	case assert.ConfigMapAssertion:
		assert.AssertPartial(t, env.GetConfigMap(t, name), a, name)
	case assert.EndpointsAssertion:
		assert.AssertPartial(t, env.GetEndpoints(t, name), a, name)
	case assert.EventAssertion:
		assert.AssertPartial(t, env.GetEvent(t, name), a, name)
	case assert.LimitRangeAssertion:
		assert.AssertPartial(t, env.GetLimitRange(t, name), a, name)
	case assert.NamespaceAssertion:
		assert.AssertPartial(t, env.GetNamespace(t, name), a, name)
	case assert.NodeAssertion:
		assert.AssertPartial(t, env.GetNode(t, name), a, name)
	case assert.PersistentVolumeAssertion:
		assert.AssertPartial(t, env.GetPersistentVolume(t, name), a, name)
	case assert.PersistentVolumeClaimAssertion:
		assert.AssertPartial(t, env.GetPersistentVolumeClaim(t, name), a, name)
	case assert.PodAssertion:
		assert.AssertPartial(t, env.GetPod(t, name), a, name)
	case assert.PodTemplateAssertion:
		assert.AssertPartial(t, env.GetPodTemplate(t, name), a, name)
	case assert.ReplicationControllerAssertion:
		assert.AssertPartial(t, env.GetReplicationController(t, name), a, name)
	case assert.ResourceQuotaAssertion:
		assert.AssertPartial(t, env.GetResourceQuota(t, name), a, name)
	case assert.SecretAssertion:
		assert.AssertPartial(t, env.GetSecret(t, name), a, name)
	case assert.ServiceAssertion:
		assert.AssertPartial(t, env.GetService(t, name), a, name)
	case assert.ServiceAccountAssertion:
		assert.AssertPartial(t, env.GetServiceAccount(t, name), a, name)
	case assert.IPAddressAssertion:
		assert.AssertPartial(t, env.GetIPAddress(t, name), a, name)
	case assert.IngressAssertion:
		assert.AssertPartial(t, env.GetIngress(t, name), a, name)
	case assert.IngressClassAssertion:
		assert.AssertPartial(t, env.GetIngressClass(t, name), a, name)
	case assert.NetworkPolicyAssertion:
		assert.AssertPartial(t, env.GetNetworkPolicy(t, name), a, name)
	case assert.ServiceCIDRAssertion:
		assert.AssertPartial(t, env.GetServiceCIDR(t, name), a, name)
	case assert.PodDisruptionBudgetAssertion:
		assert.AssertPartial(t, env.GetPodDisruptionBudget(t, name), a, name)
	case assert.ClusterRoleAssertion:
		assert.AssertPartial(t, env.GetClusterRole(t, name), a, name)
	case assert.ClusterRoleBindingAssertion:
		assert.AssertPartial(t, env.GetClusterRoleBinding(t, name), a, name)
	case assert.RoleAssertion:
		assert.AssertPartial(t, env.GetRole(t, name), a, name)
	case assert.RoleBindingAssertion:
		assert.AssertPartial(t, env.GetRoleBinding(t, name), a, name)
	case assert.CSIDriverAssertion:
		assert.AssertPartial(t, env.GetCSIDriver(t, name), a, name)
	case assert.CSINodeAssertion:
		assert.AssertPartial(t, env.GetCSINode(t, name), a, name)
	case assert.CSIStorageCapacityAssertion:
		assert.AssertPartial(t, env.GetCSIStorageCapacity(t, name), a, name)
	case assert.StorageClassAssertion:
		assert.AssertPartial(t, env.GetStorageClass(t, name), a, name)
	case assert.VolumeAttachmentAssertion:
		assert.AssertPartial(t, env.GetVolumeAttachment(t, name), a, name)
	case assert.VolumeAttributesClassAssertion:
		assert.AssertPartial(t, env.GetVolumeAttributesClass(t, name), a, name)
	default:
		t.Fatalf("env.AssertPartial: unsupported assertion type %T", assertion)
	}
}

// AssertNone asserts that the K8s resource implied by the assertion type
// does not exist. The resource type is inferred from the concrete assertion
// struct via a type switch.
func (env *Env) AssertNone(t *testing.T, name string, assertion assert.Assertable) {
	t.Helper()
	switch assertion.(type) {
	case assert.ControllerRevisionAssertion:
		_, err := env.GetControllerRevisionE(t, name)
		require.True(t, errors.IsNotFound(err), "ControllerRevision %q should not exist", name)
	case assert.DaemonSetAssertion:
		_, err := env.GetDaemonSetE(t, name)
		require.True(t, errors.IsNotFound(err), "DaemonSet %q should not exist", name)
	case assert.DeploymentAssertion:
		_, err := env.GetDeploymentE(t, name)
		require.True(t, errors.IsNotFound(err), "Deployment %q should not exist", name)
	case assert.ReplicaSetAssertion:
		_, err := env.GetReplicaSetE(t, name)
		require.True(t, errors.IsNotFound(err), "ReplicaSet %q should not exist", name)
	case assert.StatefulSetAssertion:
		_, err := env.GetStatefulSetE(t, name)
		require.True(t, errors.IsNotFound(err), "StatefulSet %q should not exist", name)
	case assert.HorizontalPodAutoscalerAssertion:
		_, err := env.GetHorizontalPodAutoscalerE(t, name)
		require.True(t, errors.IsNotFound(err), "HorizontalPodAutoscaler %q should not exist", name)
	case assert.CronJobAssertion:
		_, err := env.GetCronJobE(t, name)
		require.True(t, errors.IsNotFound(err), "CronJob %q should not exist", name)
	case assert.JobAssertion:
		_, err := env.GetJobE(t, name)
		require.True(t, errors.IsNotFound(err), "Job %q should not exist", name)
	case assert.ConfigMapAssertion:
		_, err := env.GetConfigMapE(t, name)
		require.True(t, errors.IsNotFound(err), "ConfigMap %q should not exist", name)
	case assert.EndpointsAssertion:
		_, err := env.GetEndpointsE(t, name)
		require.True(t, errors.IsNotFound(err), "Endpoints %q should not exist", name)
	case assert.EventAssertion:
		_, err := env.GetEventE(t, name)
		require.True(t, errors.IsNotFound(err), "Event %q should not exist", name)
	case assert.LimitRangeAssertion:
		_, err := env.GetLimitRangeE(t, name)
		require.True(t, errors.IsNotFound(err), "LimitRange %q should not exist", name)
	case assert.NamespaceAssertion:
		_, err := env.GetNamespaceE(t, name)
		require.True(t, errors.IsNotFound(err), "Namespace %q should not exist", name)
	case assert.NodeAssertion:
		_, err := env.GetNodeE(t, name)
		require.True(t, errors.IsNotFound(err), "Node %q should not exist", name)
	case assert.PersistentVolumeAssertion:
		_, err := env.GetPersistentVolumeE(t, name)
		require.True(t, errors.IsNotFound(err), "PersistentVolume %q should not exist", name)
	case assert.PersistentVolumeClaimAssertion:
		_, err := env.GetPersistentVolumeClaimE(t, name)
		require.True(t, errors.IsNotFound(err), "PersistentVolumeClaim %q should not exist", name)
	case assert.PodAssertion:
		_, err := env.GetPodE(t, name)
		require.True(t, errors.IsNotFound(err), "Pod %q should not exist", name)
	case assert.PodTemplateAssertion:
		_, err := env.GetPodTemplateE(t, name)
		require.True(t, errors.IsNotFound(err), "PodTemplate %q should not exist", name)
	case assert.ReplicationControllerAssertion:
		_, err := env.GetReplicationControllerE(t, name)
		require.True(t, errors.IsNotFound(err), "ReplicationController %q should not exist", name)
	case assert.ResourceQuotaAssertion:
		_, err := env.GetResourceQuotaE(t, name)
		require.True(t, errors.IsNotFound(err), "ResourceQuota %q should not exist", name)
	case assert.SecretAssertion:
		_, err := env.GetSecretE(t, name)
		require.True(t, errors.IsNotFound(err), "Secret %q should not exist", name)
	case assert.ServiceAssertion:
		_, err := env.GetServiceE(t, name)
		require.True(t, errors.IsNotFound(err), "Service %q should not exist", name)
	case assert.ServiceAccountAssertion:
		_, err := env.GetServiceAccountE(t, name)
		require.True(t, errors.IsNotFound(err), "ServiceAccount %q should not exist", name)
	case assert.IPAddressAssertion:
		_, err := env.GetIPAddressE(t, name)
		require.True(t, errors.IsNotFound(err), "IPAddress %q should not exist", name)
	case assert.IngressAssertion:
		_, err := env.GetIngressE(t, name)
		require.True(t, errors.IsNotFound(err), "Ingress %q should not exist", name)
	case assert.IngressClassAssertion:
		_, err := env.GetIngressClassE(t, name)
		require.True(t, errors.IsNotFound(err), "IngressClass %q should not exist", name)
	case assert.NetworkPolicyAssertion:
		_, err := env.GetNetworkPolicyE(t, name)
		require.True(t, errors.IsNotFound(err), "NetworkPolicy %q should not exist", name)
	case assert.ServiceCIDRAssertion:
		_, err := env.GetServiceCIDRE(t, name)
		require.True(t, errors.IsNotFound(err), "ServiceCIDR %q should not exist", name)
	case assert.PodDisruptionBudgetAssertion:
		_, err := env.GetPodDisruptionBudgetE(t, name)
		require.True(t, errors.IsNotFound(err), "PodDisruptionBudget %q should not exist", name)
	case assert.ClusterRoleAssertion:
		_, err := env.GetClusterRoleE(t, name)
		require.True(t, errors.IsNotFound(err), "ClusterRole %q should not exist", name)
	case assert.ClusterRoleBindingAssertion:
		_, err := env.GetClusterRoleBindingE(t, name)
		require.True(t, errors.IsNotFound(err), "ClusterRoleBinding %q should not exist", name)
	case assert.RoleAssertion:
		_, err := env.GetRoleE(t, name)
		require.True(t, errors.IsNotFound(err), "Role %q should not exist", name)
	case assert.RoleBindingAssertion:
		_, err := env.GetRoleBindingE(t, name)
		require.True(t, errors.IsNotFound(err), "RoleBinding %q should not exist", name)
	case assert.CSIDriverAssertion:
		_, err := env.GetCSIDriverE(t, name)
		require.True(t, errors.IsNotFound(err), "CSIDriver %q should not exist", name)
	case assert.CSINodeAssertion:
		_, err := env.GetCSINodeE(t, name)
		require.True(t, errors.IsNotFound(err), "CSINode %q should not exist", name)
	case assert.CSIStorageCapacityAssertion:
		_, err := env.GetCSIStorageCapacityE(t, name)
		require.True(t, errors.IsNotFound(err), "CSIStorageCapacity %q should not exist", name)
	case assert.StorageClassAssertion:
		_, err := env.GetStorageClassE(t, name)
		require.True(t, errors.IsNotFound(err), "StorageClass %q should not exist", name)
	case assert.VolumeAttachmentAssertion:
		_, err := env.GetVolumeAttachmentE(t, name)
		require.True(t, errors.IsNotFound(err), "VolumeAttachment %q should not exist", name)
	case assert.VolumeAttributesClassAssertion:
		_, err := env.GetVolumeAttributesClassE(t, name)
		require.True(t, errors.IsNotFound(err), "VolumeAttributesClass %q should not exist", name)
	default:
		t.Fatalf("env.AssertNone: unsupported assertion type %T", assertion)
	}
}
