apiVersion: v1
kind: ConfigMap
metadata:
  name: zitadel-config-yaml
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
data:
  zitadel-config-yaml: |-
    {{ .Values.zitadel.configmapConfig | toYaml | nindent 4 }}
