#file: noinspection HttpUrlsUsage
# -----------------------------------------------------------------------------
# This ConfigMap defines the NGINX configuration for the LOGIN sidecar. It is
# used by the additional "nginx-ssl" container that runs alongside the Zitadel
# Login deployment. The sidecar is responsible for handling TLS termination and
# forwarding requests to the login service.
# -----------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zitadel.login.fullname" . }}-nginx
  labels:
    {{- include "zitadel.login.labels" . | nindent 4 }}
data:
  default.conf: |
    # Nginx proxies to the NextJS login app on the internal NextJS port (port 3000)
    # This port is hardcoded and not user-configurable
    upstream login_app {
      server 127.0.0.1:{{- include "login.nextjsPort" . -}};
    }

    {{- if include "login.tlsEnabled" . }}
    server {
      # Nginx listens on the configured port for HTTPS with HTTP/2 support
      listen {{ include "login.nginxPort" . }} ssl http2;
      ssl_certificate     /etc/nginx/certs/tls.crt;
      ssl_certificate_key /etc/nginx/certs/tls.key;

      location /healthz {
        return 200 "ok\n";
      }

      location / {
        proxy_pass http://login_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto https;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
      }
    }
    {{- else }}
    server {
      # Nginx listens on the configured port for HTTP with HTTP/2 support
      listen {{ include "login.nginxPort" . }} http2;

      location /healthz {
        return 200 "ok\n";
      }

      location / {
        proxy_pass http://login_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto http;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
      }
    }
    {{- end }}
