{{- if .Values.login.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "login.configmapName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.login.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "login.labels" . | nindent 4 }}
data:
  .env: |-
    {{- if .Values.login.customConfigmapConfig }}
    {{ .Values.login.customConfigmapConfig | nindent 4 }}
    {{- else }}
      ZITADEL_LOGINCLIENT_KEYFILE="/login-service-key/tls.key"
      {{- $extPort := int (.Values.zitadel.configmapConfig.ExternalPort | default .Values.service.port) }}
      {{- $extSecure := .Values.zitadel.configmapConfig.ExternalSecure }}
      {{- $isDefaultPort := or (and $extSecure (eq $extPort 443)) (and (not $extSecure) (eq $extPort 80)) (eq $extPort 0) }}
      AUDIENCE="http{{ if $extSecure }}s{{ end }}://{{ .Values.zitadel.configmapConfig.ExternalDomain }}{{ if not $isDefaultPort }}:{{ $extPort }}{{ end }}"
      ZITADEL_API_URL="http{{ if and .Values.zitadel.configmapConfig.TLS .Values.zitadel.configmapConfig.TLS.Enabled }}s{{ end }}://{{ include "zitadel.fullname" . }}:{{ .Values.service.port }}"
      CUSTOM_REQUEST_HEADERS="Host:{{ .Values.zitadel.configmapConfig.ExternalDomain }},X-Zitadel-Public-Host:{{ .Values.zitadel.configmapConfig.ExternalDomain }}"
      {{- if .Values.zitadel.selfSignedCert.enabled }}
      NODE_TLS_REJECT_UNAUTHORIZED=0
      {{- end }}
    {{- end }}
{{- end }}
