{{- if .Values.gateway.grpcRoute.enabled -}}
{{- $fullName := include "zitadel.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $externalDomain := .Values.zitadel.configmapConfig.ExternalDomain -}}
{{- $filters := .Values.gateway.grpcRoute.filters -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ $fullName }}-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
    {{- with .Values.gateway.grpcRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.grpcRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gateway.grpcRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.gateway.grpcRoute.hostnames $externalDomain }}
  hostnames:
    {{- if .Values.gateway.grpcRoute.hostnames }}
    {{- range .Values.gateway.grpcRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
    {{- else }}
    - {{ $externalDomain | quote }}
    {{- end }}
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
      {{- with $filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
