{{- if .Values.cleanupJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "zitadel.fullname" . }}-cleanup"
  labels:
    {{- include "zitadel.cleanup.labels" . | nindent 4 }}
  {{- with .Values.cleanupJob.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ .Values.cleanupJob.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.cleanupJob.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "zitadel.cleanup.labels" . | nindent 8 }}
        {{- with .Values.cleanupJob.podAdditionalLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.cleanupJob.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zitadel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      enableServiceLinks: false
      restartPolicy: Never
      containers:
        - name: "{{ .Chart.Name }}-cleanup"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 14 }}
          image: "alpine/k8s:{{ include "zitadel.kubeVersion" . }}"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "Cleaning up secrets created by zitadel-setup..."
              kubectl --namespace={{ .Release.Namespace }} delete secret \
                --selector='app.kubernetes.io/managed-by=Zitadel,app.kubernetes.io/instance={{ .Release.Name }}' \
                --ignore-not-found=true
              echo "Cleanup completed"
          resources:
            {{- toYaml .Values.cleanupJob.resources | nindent 14 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
