{{- if .Values.pdb.enabled }}
{{- if semverCompare "<=1.22-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: policy/v1beta1
{{- else -}}
apiVersion: policy/v1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "zitadel.fullname" . }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
  {{- with .Values.pdb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # test if both are set and if so return error
  {{- if and .Values.pdb.minAvailable .Values.pdb.maxUnavailable }}
  {{- fail "You can only set either minAvailable or maxUnavailable" }}
  {{- end }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zitadel.selectorLabels" . | nindent 6 }}
{{- end }}
