{{- if include "deepCheck" (dict "root" .Values "path" (splitList "." "zitadel.configmapConfig.FirstInstance.Org.Machine")) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zitadel.serviceAccountName" . }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "create" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zitadel.serviceAccountName" . }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
subjects:
  - kind: ServiceAccount
    name:  {{ include "zitadel.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "zitadel.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end}}