{{- if .Values.zitadel.dbSslRootCrt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-ssl-root-crt
  {{- if not .Release.IsInstall -}}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
  {{- end -}}
stringData:
  ca.crt: |-
{{ .Values.zitadel.dbSslRootCrt | default "" | nindent 6 }}
{{- end }}