{{- $cn := printf "%s-adminapi" (include "zitadel.fullname" .) }}
{{- $cert := genSelfSignedCert $cn nil (list $cn) 3650 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zitadel.fullname" . }}-adminapi-key
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
