{{- if (or (and .Values.login.loginClientSecretName .Values.login.loginClientSecretPrivateKeyValue) (and (not .Values.login.loginClientSecretPrivateKeyValue) (not .Values.login.loginClientSecretName)) ) }}
{{- fail "Either set .Values.login.loginClientSecretPrivateKeyValue xor .Values.login.loginClientSecretName" }}
{{- end }}
{{- if .Values.zitadel.masterkey -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "login.loginClientSecretName" . }}
  {{- with .Values.login.loginClientSecretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "zitadel.labels" . | nindent 4 }}
stringData:
  "login-client-private-key": {{ .Values.login.loginClientSecretPrivateKeyValue }}
  "login-client-public-key": {{ .Values.login.loginClientSecretPublicKeyValue }}
{{- end -}}
