{{- if and .Values.login.enabled .Values.login.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "login.serviceAccountName" . }}
  labels:
    {{- include "login.labels" . | nindent 4 }}
  {{- with .Values.login.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
