apiVersion: v1
kind: Secret
metadata:
  name: existing-zitadel-masterkey
type: Opaque
stringData:
  # Must be exactly 32 ASCII characters. Do NOT use hex or base64 encoding.
  # Generate with: tr -dc A-Za-z0-9 </dev/urandom | head -c 32
  masterkey: "x123456789012345678901234567891y"
