logs:
  general:
    level: DEBUG
additionalArguments:
  - "--serverstransport.insecureskipverify=true"
service:
  type: NodePort
ports:
  web:
    nodePort: 30080
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    nodePort: 30443
ingressClass:
  enabled: true
  isDefaultClass: true
