image:
  repository: bitnamilegacy/postgresql

metrics:
  image:
    repository: bitnamilegacy/postgres-exporter

volumePermissions:
  image:
    repository: bitnamilegacy/os-shell

primary:
  persistence:
    enabled: false
  pgHbaConfiguration: |
    host all all all trust
