#file: noinspection KubernetesUnknownResourcesInspection
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-pg
spec:
  instances: 1

  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: zitadel
      owner: zitadel
      secret:
        name: zitadel-pg-user

  superuserSecret:
    name: zitadel-pg-superuser

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
