zitadel:
  masterkey: x123456789012345678901234567891y
  configmapConfig:
    ExternalSecure: false
    TLS:
      Enabled: false
  secretConfig:
    Database:
      postgres:
        Host: db-postgresql
        Port: 5432
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: zitadel
          Password: "xyz"
          SSL:
            Mode: disable
        Admin:
          Username: postgres
          Password: "abc"
          SSL:
            Mode: disable
  dbSslRootCrtSecret: ""
  dbSslClientCrtSecret: ""
