name: Qodana

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: ./

jobs:
  qodana-check:
    runs-on: ubuntu-latest
    name: Inspect Code

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2025.3
        with:
          args: --baseline,.qodana/qodana.sarif.json
          push-fixes: true
        env:
          GOTOOLCHAIN: auto
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
